### ISSUE TITLE
这个解析逻辑为什么获取accesstoken逻辑为什么要调用接口？

### ISSUE THREAD

**Issue by rayshen92** [wozulong/ChatGPTAuthHelper#5]
<img width="801" alt="image" src="https://github.com/wozulong/ChatGPTAuthHelper/assets/38471614/a2d7488a-c04e-4dca-8984-15767bb2ac75">

这不是有泄漏token的风险？

**Comment by wozulong** [comment]
不然应该怎么写，你教教我？

**Comment by rayshen92** [comment]
> 不然应该怎么写，你教教我？

我的意思是解析逻辑不能放到浏览器做吗？

**Comment by rayshen92** [comment]
或者能公开下接口的后台逻辑吗

**Comment by wozulong** [comment]
接口把ip封锁部分要做的事做了。如果你ip是被封锁的，浏览器即便能操作有什么意义呢？这个插件就不具有通用性。如果你ip没被封锁，你也没理由用这个插件啊。
