### ISSUE TITLE
chrome bug

### ISSUE THREAD

**Issue by Dr0sophila** [wozulong/ChatGPTAuthHelper#7]
我在使用chrome浏览器尝试使用token登入时出现了bug
POST https://chat.zhile.io/auth/login_token 400 (Bad Request)
但是在firefox中可以正常使用你们的服务 
![捕获](https://github.com/wozulong/ChatGPTAuthHelper/assets/80738220/9fd82936-e758-4b9f-bb82-9ef42cdce680)

**Comment by wozulong** [comment]
这似乎是很久之前的页面了，你浏览器缓存了。

**Comment by Dr0sophila** [comment]
解决了，感谢你的帮助
